version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: rentx
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    depends_on:
      - db
    network_mode: host

volumes:
  pgdata:
